name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: buchstabensuppe
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      # permission change taken from curry-club-augsburg.de
      - name: Build web output
        run: |
          nix-build doc/web.nix
          cp -RL result tmp
          chmod -R +w tmp
      - name: Deploy output to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: tmp
